import { Inter } from 'next/font/google'
import './globals.css'
import './style.css'
import { ChakraProvider } from '@chakra-ui/react'
import { UserProvider } from '../../context/user'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraProvider>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </ChakraProvider>
    </html>
  )
}
